#!/usr/sbin/nft -f
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        iif lo accept
        ct state established,related accept

        # SSH from nginx (bastion) only
        ip saddr 10.0.2.113 tcp dport 22 accept

        # API port from nginx only
        ip saddr 10.0.2.113 tcp dport 3000 accept
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
    }
}
